FROM php:8.2-cli

# Cài extension cần thiết (FIX LỖI Ở ĐÂY)
RUN docker-php-ext-install bcmath pdo pdo_mysql

# Cài composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /app
COPY . .

# Debug xem có bcmath chưa
RUN php -m | grep bcmath

# Cài dependencies
RUN composer install --no-interaction --optimize-autoloader

# Chạy Laravel
CMD php artisan serve --host=0.0.0.0 --port=$PORT