FROM php:8.2-cli

# Cài lib + extension cần thiết
RUN apt-get update && apt-get install -y \
    git unzip curl libzip-dev zip \
    && docker-php-ext-install \
        bcmath \
        pdo \
        pdo_mysql \
        zip

# Cài Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /app
COPY . .

# Install dependency (❌ bỏ --no-scripts)
RUN composer install \
    --no-interaction \
    --prefer-dist \
    --optimize-autoloader

# Copy env nếu chưa có
RUN cp .env.example .env || true

# Generate key
RUN php artisan key:generate || true

# Cache config
RUN php artisan config:cache || true

# Expose port
EXPOSE 8000

# Start app
CMD php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT